### ISSUE TITLE
Bug in AlphaBeta rule?

### ISSUE THREAD

**Issue by nkoenen** [chr5tphr/zennit#107]
Hi,

I've been working very extensively with the LRP method lately and I also tried to implement the method with the most commonly used rules by myself. In order to check the correctness of my implementation, I compared some results with already existing implementations (like yours ;) ). Thereby I always get different relevances with the AlphaBeta-rule (I already opened an [issue](https://github.com/albermax/innvestigate/issues/273#issue-1065751561) in innvestigate with the same example). Maybe you can explain the following behavior or confirm that this is really a bug on your side:

Let's suppose we have only one layer with two inputs, one output and no activation function. The layer has the following weights and bias vector: W = (1, -1) and b = -1. For the input x = (1,1), the formula of the AlphaBeta rule (Eq. (60)) in [Bach et al.](https://doi.org/10.1371/journal.pone.0130140) reduces to  (in this case is r_out = -1)
-  r1 = alpha * (1 * 1 / (1 * 1)) + beta * (0 / -1)  * r_out = alpha * r_out
- r2 = alpha * (0 / 1) + beta * ((1 * -1) / (1 * -1 + (-1))) * r_out = beta * 0.5 * r_out

This yields a relevance of (-1, 0) for the Alpha1_Beta0-rule and (-2,  0.5) for the Alpha2_Beta1-rule. But with your implementation I get both times (0.5, -0.5). Also for other choices of alpha and beta I always get the same result. Here is my code snippet for the Alpha1_Beta0 rule:

```python
import torch
import torch.nn as nn
from zennit.rules import AlphaBeta

input = torch.tensor([[1.,1.]], requires_grad = True)

model = nn.Sequential(
      nn.Linear(2, 1)
  )
model.get_submodule("0").weight.data = torch.tensor([[1., -1.]])
model.get_submodule("0").bias.data = torch.tensor([-1.])

rule = AlphaBeta(alpha = 1, beta = 0)
rule.register(model)
output = model(input)

grad_out = torch.ones_like(output) * output

attr, = torch.autograd.grad(
    output, input, grad_outputs=grad_out
)

attr
# tensor([[ 0.5000, -0.5000]])
```

I hope you can help me to clarify this behavior.

Best Niklas

**Comment by chr5tphr** [comment]
Hey Niklas,

the problem is that you try to register the rule to the `Sequential` model itself, instead of the Linear layer, which will not work. I'm actually surprised this does not crash.

Here's two ways to do it, one with only a single layer:
<details>
  <summary>Single Linear Code</summary>
  
```python
import torch
from torch.nn import Linear
from zennit.rules import AlphaBeta

print('Layer-only:')
for alpha, beta in [(1., 0.), (2., 1.)]:
    print(f'  alpha={alpha}, beta={beta}')
    layer = Linear(2, 1)
    layer.weight.data = torch.tensor([[1., -1.]])
    layer.bias.data = torch.tensor([-1.])

    input = torch.tensor([[1., 1.]], requires_grad=True)
    # create hook and immediately register to layer
    handle = AlphaBeta(alpha=alpha, beta=beta).register(layer)
    output = layer(input)
    relevance, = torch.autograd.grad(output, input, grad_outputs=output)
    # remove the hook from the layer
    handle.remove()
    print(f'    {relevance}')
```
  
</details>

which prints:
<details>
  <summary>Single Linear Output</summary>
  
 ```
Layer-only:
  alpha=1.0, beta=0.0
    tensor([[-1.0000,  0.0000]])
  alpha=2.0, beta=1.0
    tensor([[-2.0000,  0.5000]])
```
</details>


and one with the full Sequential, using a custom Composite and Attributor:
<details>
  <summary>Sequential Code</summary>
  
```python
import torch
from torch.nn import Linear, Sequential
from zennit.rules import AlphaBeta
from zennit.attribution import Gradient
from zennit.composites import LayerMapComposite


print('Custom Composite:')
for alpha, beta in [(1., 0.), (2., 1.)]:
    print(f'  alpha={alpha}, beta={beta}')
    layer = Linear(2, 1)
    layer.weight.data = torch.tensor([[1., -1.]])
    layer.bias.data = torch.tensor([-1.])
    # create a custom composite, which maps Linear layers to AlphaBeta
    composite = LayerMapComposite([((Linear,), AlphaBeta(alpha=alpha, beta=beta))])

    # create a simple Sequential model with a single layer
    model = Sequential(layer)
    # use the Gradient attributor on the model with our custom composite
    with Gradient(model, composite) as attributor:
        out, relevance = attributor(input)

    print(f'    {relevance}')
```
</details>

which prints:
<details>
  <summary>Sequential Output</summary>
  
```
Custom Composite:
  alpha=1.0, beta=0.0
    tensor([[-1.0000,  0.0000]])
  alpha=2.0, beta=1.0
    tensor([[-2.0000,  0.5000]])
```
</details>

which is both what you computed by hand.

Have a look at the [documentation](https://zennit.readthedocs.io/en/latest/how-to/use-rules-composites-and-canonizers.html), where there is also an example with only a single layer.

**Comment by nkoenen** [comment]
Awesome! Thank you for the quick reply.
