### ISSUE TITLE
Composite: bug in BetaSmooth constructor?

### ISSUE THREAD

**Issue by annahdo** [chr5tphr/zennit#172]
Hi,

I noticed that the `beta_smooth` parameter is not passed to the `ReLUBetaSmooth` hook when initializing the `BetaSmooth` composite in [composites.py](../blob/master/src/zennit/composites.py). This results in the default use of `beta_smooth=10` at all times. I assume that's not intended, or am I missing sth?

Best

**Comment by chr5tphr** [comment]
Hey @annahdo 

good catch, that's indeed not intended, thank you for the issue!
Would you like to open a Pull Request for the fix yourself, where the parameter is correctly passed?

**Comment by annahdo** [comment]
sure, I'll do that.

**Comment by chr5tphr** [comment]
Done in #173
