### ISSUE TITLE
Bug: MultiheadAttention in types

### ISSUE THREAD

**Issue by rachtibat** [chr5tphr/zennit#188]
Hi,

[here](https://github.com/chr5tphr/zennit/blob/3121bb223061506834ca68abad3eefc792dea999/src/zennit/types.py#L111) for some mysterious reason the nn.MultiheadAttention is part of the Activation types.

I am actually implementing a canonizer for this module and then it just didn't trigger and I was wondering what is happening until I found out that the layer_base automatically overwrites my rule with the Pass() one (;

Best,
Reduan

**Comment by chr5tphr** [comment]
Hey Reduan,

yes, good catch!
If you would like to open a PR, you can remove it from [`src/zennit/types.py:111`](https://github.com/chr5tphr/zennit/blob/3121bb223061506834ca68abad3eefc792dea999/src/zennit/types.py#L111).

**Comment by rachtibat** [comment]
Hey,

yes, I can do it. It might take two weeks as I'm going to a conference now.

Best

**Comment by rachtibat** [comment]
Thanks for your patience.
I opened a pull request #191

**Comment by chr5tphr** [comment]
Merged.
