### ISSUE TITLE
Notebook for feed_forward.py

### ISSUE THREAD

**Issue by heytitle** [chr5tphr/zennit#24]
Hi,

I'm playing with `zennit` at the moment; usually, I like to start with a simple notebook. So, I made such a notebook for myself based on `share/examples/feed_forward.py`.

Perhaps, we can convert it to be a tutorial of the package. 

https://colab.research.google.com/drive/1MNLkfMi9DB9lZkkcOPOodQhXCatkwQgO#scrollTo=LIGiH5SP8IC4

**Comment by chr5tphr** [comment]
Hey Pat,

thank you for sharing the notebook! I'm currently working on the documentation with sphinx, and adding ipynbs as tutorials through `nbsphinx` is the way to go (e.g. see [here](https://qiskit.org/documentation/tutorials/circuits/01_circuit_basics.html)).

Let's keep this issue open until we have the proper tutorial.

**Comment by linghu258** [comment]
Hi, thanks for the tutorial notebook on how to use the zennit. I was wondering if there are any notebook for the resnet model implementation as well ? I tried changing to resnet50 and ResNetCanonizer but the heatmap displayed a solid colour instead.

**Comment by chr5tphr** [comment]
> Hi, thanks for the tutorial notebook on how to use the zennit. I was wondering if there are any notebook for the resnet model implementation as well ? I tried changing to resnet50 and ResNetCanonizer but the heatmap displayed a solid colour instead.

Hey Joel,

did you use EpsilonGammaBox with ResNet(50)?
We have observed EpsilonGammaBox not really working nicely with ResNet, if I recall correctly using the gradient instead of the norm for the sum for the residual connections might work better for that particular composite.

Otherwise I think using EpsilonPlus or EpsilonAlpha2Beta1Flat are better choices.

<details>
  <summary>ResNet50 Heatmaps (click to unfold)</summary>
  
  ![image](https://user-images.githubusercontent.com/15217558/124110315-61f78f00-da68-11eb-9938-8db7da33cc74.png)

</details>

**Comment by linghu258** [comment]
Thanks for the response. Yes, I did use EpsilonGammaBox with ResNet(50). I've tried changing EpsilonGammaBox to either  EpsilonPlus or EpsilonAlpha2Beta1Flat, but I have encountered an error (shown below). I've also tried changing SequentialMergeBatchNorm as the canonizer but was to no avail.

---> 28 composite = COMPOSITES[composite_name](**composite_kwargs )

TypeError: __init__() got an unexpected keyword argument 'low'

**Comment by chr5tphr** [comment]
> Thanks for the response. Yes, I did use EpsilonGammaBox with ResNet(50). I've tried changing EpsilonGammaBox to either EpsilonPlus or EpsilonAlpha2Beta1Flat, but I have encountered an error (shown below). I've also tried changing SequentialMergeBatchNorm as the canonizer but was to no avail.
> 
> ---> 28 composite = COMPOSITES[composite_name](**composite_kwargs)
> 
> TypeError: **init**() got an unexpected keyword argument 'low'

The "high" and "low" keyword arguments are ZBox-rule-specific (the "Box" part of EpsilonGammaBox).

Maybe also take a look at the original [example](https://github.com/chr5tphr/zennit/blob/master/share/example/feed_forward.py), which is a little more general than the notebook.

Simply change
```python
composite_kwargs = dict(     
    # the highest and lowest pixel values for the ZBox rule
    low=norm_fn(torch.zeros(*shape, device=device)),
    high=norm_fn(torch.ones(*shape, device=device))
)
```

to
```python
composite_kwargs = {}
```

and you should be able to use the other rules.

**Comment by linghu258** [comment]
Hi, thanks again for the response. After looking through the linked original example. I'm wondering why I can't use other heatmap variants other than epsilon ? such as the guided_backprop or smoothgrad which seem to produce a better heatmap then epsilon_plus or epsilon_alpha2_beta1_flat

**Comment by sebastian-lapuschkin** [comment]
Dear @linghu258 ,

answered in #40 .

Please do not overload the topics of individual issues, feel free to create a new one if it seems reasonable.

**Comment by chr5tphr** [comment]
There is now an [official notebook](https://zennit.readthedocs.io/en/latest/tutorial/image-classification-vgg.html) for image classification with VGG, so I am closing this issue.
