### ISSUE TITLE
torch 1.10 version not working

### ISSUE THREAD

**Issue by rachtibat** [chr5tphr/zennit#60]
Hi Chris,

it seems that the pytorch version 1.10 produces wrong heatmaps and maybe also newer versions of torch.
I updated my conda environment and suddenly the "epsilon_plus_flat" rule did not work anymore.
Returning to
`pip install torch=1.9 torchvision=0.10`
fixed the issue.

Best

**Comment by chr5tphr** [comment]
Hey Reduan,

thank you for raising this issue. I'm currently still quite sick, so I cannot fix this right away, but I will work on it as soon as I'm feeling better again.
Until then, I guess torch 1.9.x of torch should be used. Let's hope the fix for 1.10 will not break compatibility for 1.9.

**Comment by rachtibat** [comment]
Hi Chris, 

I wish you a speedy recovery! Take it easy, it is not important.
