### ISSUE TITLE
Feature request: Support for max-pooling layers

### ISSUE THREAD

**Issue by rodrigobdz** [chr5tphr/zennit#77]
In the code there seems to be no mention of max-pooling layers, is LRP for this type of layers already (implicitly) supported?

**Comment by chr5tphr** [comment]
Hey Rodrigo,
Max-Pooling are supported, as its gradient distributes the relevance in the correct way for LRP, ie. winner-takes-all.

**Comment by rodrigobdz** [comment]
Hi, Christopher, thanks for your prompt reply. 
I see, proceeding to close this issue then.
